using California.Creator.Service.Models.Core;
using System;
using System.Collections.Generic;
using System.Text;

namespace California.Creator.Service.Options
{
    public class CaliforniaServiceOptions
    {
        // --- requires restart after change ---
        public enum DbEngineSelector { Mssql, Sqlite }
        public DbEngineSelector DatabaseTechnology { get; set; } = DbEngineSelector.Mssql; // value is selected by chosing appropriate service register routines
        public string EmailDomainName { get; set; } = "xn--xckd0d.com"; // TODO
        public Dictionary<StyleAtomType, List<string>> StyleAtomDefaultProperties = new Dictionary<StyleAtomType, List<string>>();
        public const string ServerApplicationName = "California";
        public string CookieName { get; set; } = $".{ServerApplicationName}Service.UNSET";
        public const int AutoGeneratedCssClassesMaxLength = 10000;
        // ---

        // --- requires database migration after change ---
        public const int UserDefinedCssMaxLength = 12500; // * UTF-8 bytes \approx 100kB, TODO file-based import for bigger css
        // ---
    }
}
