export const TIMELINE_COLOR_R: number = 14; // DARKBLUE
export const TIMELINE_COLOR_G: number = 30;
export const TIMELINE_COLOR_B: number = 86;
export const TIMELINE_COLOR_STRING: string = `rgb(${TIMELINE_COLOR_R},${TIMELINE_COLOR_G},${TIMELINE_COLOR_B})`; // TODO constant is automatically generated?
export const TIMELINE_SHADED_COLOR_R: number = 200; // DARKBLUE (SHADED)
export const TIMELINE_SHADED_COLOR_G: number = 0;
export const TIMELINE_SHADED_COLOR_B: number = 0;
export const TIMELINE_SHADED_COLOR_STRING: string = `rgb(${TIMELINE_SHADED_COLOR_R},${TIMELINE_SHADED_COLOR_G},${TIMELINE_SHADED_COLOR_B})`; // TODO constant is automatically generated?
export const TIMELINE_HIGHLIGHT_COLOR_R: number = 255; // RED
export const TIMELINE_HIGHLIGHT_COLOR_G: number = 0;
export const TIMELINE_HIGHLIGHT_COLOR_B: number = 0;
export const TIMELINE_HIGHLIGHT_COLOR_STRING: string = `rgb(${TIMELINE_HIGHLIGHT_COLOR_R},${TIMELINE_HIGHLIGHT_COLOR_G},${TIMELINE_HIGHLIGHT_COLOR_B})`; // TODO constant is automatically generated?
export const TIMELINE_INTERMEDIATE_COLOR_R: number = 42; // CYAN
export const TIMELINE_INTERMEDIATE_COLOR_G: number = 178;
export const TIMELINE_INTERMEDIATE_COLOR_B: number = 191;
export const TIMELINE_INTERMEDIATE_COLOR_STRING: string = `rgb(${TIMELINE_INTERMEDIATE_COLOR_R},${TIMELINE_INTERMEDIATE_COLOR_G},${TIMELINE_INTERMEDIATE_COLOR_B})`; // TODO constant is automatically generated?
export const TIMELINE_WARNING_COLOR_R: number = 242; // Yellow
export const TIMELINE_WARNING_COLOR_G: number = 242;
export const TIMELINE_WARNING_COLOR_B: number = 0;
export const TIMELINE_WARNING_COLOR_STRING: string = `rgb(${TIMELINE_WARNING_COLOR_R},${TIMELINE_WARNING_COLOR_G},${TIMELINE_WARNING_COLOR_B})`; // TODO constant is automatically generated?
export const INTERACTION_AREA_BG_COLOR_STRING: string = "rgb(233, 236, 239)";
export const TIMELINE_MIN_WIDTH_PX: number = 1150;// TODO document adjust with element widths, counts // TODO reduce to <1000px
export const TIMELINE_MIN_WIDTH_STRING: string = `${TIMELINE_MIN_WIDTH_PX}px`;
export const TIMELINE_HEIGHT_PX: number = 80;
export const TIMELINE_HEIGHT_PX_STRING: string = `${TIMELINE_HEIGHT_PX}`;